# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtp_protocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rtp_protocol.proto',
  package='rtp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12rtp_protocol.proto\x12\x03rtp\"\x91\x01\n\x08RTPSetup\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x11\n\tserver_ip\x18\x02 \x01(\t\x12\x13\n\x0bserver_port\x18\x03 \x01(\x05\x12\x11\n\tclient_ip\x18\x04 \x01(\t\x12\x13\n\x0b\x63lient_port\x18\x05 \x01(\x05\x12\x13\n\x0bpacket_size\x18\x06 \x01(\x05\x12\r\n\x05\x63odec\x18\x07 \x01(\t\"[\n\tRTPPacket\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"x\n\nRTPControl\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.rtp.RTPControl.ControlType\",\n\x0b\x43ontrolType\x12\x08\n\x04PLAY\x10\x00\x12\t\n\x05PAUSE\x10\x01\x12\x08\n\x04STOP\x10\x02\x62\x06proto3'
)



_RTPCONTROL_CONTROLTYPE = _descriptor.EnumDescriptor(
  name='ControlType',
  full_name='rtp.RTPControl.ControlType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLAY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAUSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=344,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_RTPCONTROL_CONTROLTYPE)


_RTPSETUP = _descriptor.Descriptor(
  name='RTPSetup',
  full_name='rtp.RTPSetup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='rtp.RTPSetup.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_ip', full_name='rtp.RTPSetup.server_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_port', full_name='rtp.RTPSetup.server_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_ip', full_name='rtp.RTPSetup.client_ip', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_port', full_name='rtp.RTPSetup.client_port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_size', full_name='rtp.RTPSetup.packet_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codec', full_name='rtp.RTPSetup.codec', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=173,
)


_RTPPACKET = _descriptor.Descriptor(
  name='RTPPacket',
  full_name='rtp.RTPPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='rtp.RTPPacket.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='rtp.RTPPacket.sequence_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rtp.RTPPacket.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='rtp.RTPPacket.payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=266,
)


_RTPCONTROL = _descriptor.Descriptor(
  name='RTPControl',
  full_name='rtp.RTPControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='rtp.RTPControl.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='rtp.RTPControl.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RTPCONTROL_CONTROLTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=388,
)

_RTPCONTROL.fields_by_name['type'].enum_type = _RTPCONTROL_CONTROLTYPE
_RTPCONTROL_CONTROLTYPE.containing_type = _RTPCONTROL
DESCRIPTOR.message_types_by_name['RTPSetup'] = _RTPSETUP
DESCRIPTOR.message_types_by_name['RTPPacket'] = _RTPPACKET
DESCRIPTOR.message_types_by_name['RTPControl'] = _RTPCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RTPSetup = _reflection.GeneratedProtocolMessageType('RTPSetup', (_message.Message,), {
  'DESCRIPTOR' : _RTPSETUP,
  '__module__' : 'rtp_protocol_pb2'
  # @@protoc_insertion_point(class_scope:rtp.RTPSetup)
  })
_sym_db.RegisterMessage(RTPSetup)

RTPPacket = _reflection.GeneratedProtocolMessageType('RTPPacket', (_message.Message,), {
  'DESCRIPTOR' : _RTPPACKET,
  '__module__' : 'rtp_protocol_pb2'
  # @@protoc_insertion_point(class_scope:rtp.RTPPacket)
  })
_sym_db.RegisterMessage(RTPPacket)

RTPControl = _reflection.GeneratedProtocolMessageType('RTPControl', (_message.Message,), {
  'DESCRIPTOR' : _RTPCONTROL,
  '__module__' : 'rtp_protocol_pb2'
  # @@protoc_insertion_point(class_scope:rtp.RTPControl)
  })
_sym_db.RegisterMessage(RTPControl)


# @@protoc_insertion_point(module_scope)
